import {
  QTE_STYLE_DEFAULTS,
  resolveQteStyle,
  type QteResolvedStyle,
} from "./qte-style";

export type QtePresetCategory = "基础" | "动作" | "幻想" | "氛围";

export interface QteStylePreset {
  id: string;
  name: string;
  category: QtePresetCategory;
  description: string;
  style: QteResolvedStyle;
}

function preset(
  id: string,
  name: string,
  category: QtePresetCategory,
  description: string,
  patch: Partial<QteResolvedStyle>,
): QteStylePreset {
  return {
    id,
    name,
    category,
    description,
    style: resolveQteStyle({ ...QTE_STYLE_DEFAULTS, ...patch }),
  };
}

/** Complete built-in skins. Applying one writes every field, avoiding hybrids. */
export const QTE_STYLE_PRESETS: readonly QteStylePreset[] = [
  preset("classic-focus", "经典聚焦", "基础", "清晰、克制，适合通用剧情判定。", {}),
  preset("cinema-minimal", "电影极简", "基础", "无刻度的细线界面，弱化游戏化装饰。", {
    overlayColor: "#00000038",
    outerRingColor: "#FFFFFFE6",
    outerTrackColor: "#FFFFFF17",
    perfectColor: "#FFFFFF",
    tickColor: "#FFFFFF00",
    buttonBgColor: "#0A0A0ABF",
    buttonAccentColor: "#FFFFFF",
    promptBgColor: "#00000000",
    progressColor: "#FFFFFF8A",
    ringStroke: 2,
    ringGlow: 8,
    tickCount: 0,
    buttonSize: 74,
    buttonBorderWidth: 1,
    buttonFontSize: 24,
    buttonShadow: 12,
    buttonPulse: 2,
    promptFontSize: 15,
    promptLetterSpacing: 3,
    promptWeight: "regular",
    flashIntensity: 42,
    ambientGlow: 18,
    sparkCount: 0,
  }),
  preset("neon-pulse", "霓虹脉冲", "动作", "青紫双辉光与高速分段环，适合赛博场景。", {
    overlayColor: "#07051C70",
    overlayBlur: 2,
    outerRingColor: "#42F5EFFF",
    outerTrackColor: "#865DFF2E",
    perfectColor: "#FF4FD8FF",
    tickColor: "#42F5EFA6",
    buttonBgColor: "#100B2CF2",
    buttonTextColor: "#F2FFFF",
    buttonBorderColor: "#42F5EFCC",
    buttonAccentColor: "#FF4FD8",
    promptColor: "#E8FFFF",
    promptBgColor: "#0B0827D9",
    progressColor: "#42F5EF",
    flashColor: "#FF4FD8CC",
    ringPattern: "segmented",
    ringStroke: 8,
    ringGlow: 54,
    ringRotationSpeed: 50,
    tickCount: 16,
    tickLength: 13,
    buttonSize: 96,
    buttonBorderWidth: 2,
    buttonFontSize: 34,
    buttonShadow: 38,
    buttonPulse: 8,
    promptLetterSpacing: 2.4,
    flashSize: 230,
    flashIntensity: 90,
    ambientGlow: 92,
    sparkCount: 16,
    motionSpeed: 1.35,
  }),
  preset("danger-lock", "危机锁定", "动作", "红白警报、方形准星和强烈收缩感。", {
    overlayColor: "#16030575",
    outerRingColor: "#FFEEEFFF",
    outerTrackColor: "#FF3E4D33",
    perfectColor: "#FF3448",
    tickColor: "#FF6875CC",
    buttonBgColor: "#33070BF2",
    buttonTextColor: "#FFF4F4",
    buttonBorderColor: "#FF5261E6",
    buttonAccentColor: "#FF3448",
    promptColor: "#FFF4F4",
    promptBgColor: "#4A080CE8",
    progressColor: "#FF8790",
    flashColor: "#FF3448D9",
    ringShape: "rounded-square",
    ringPattern: "dashed",
    buttonShape: "rounded",
    promptWeight: "bold",
    ringDiameter: 300,
    ringStroke: 7,
    ringGlow: 46,
    ringRotationSpeed: -30,
    tickCount: 8,
    tickLength: 18,
    buttonSize: 92,
    buttonBorderWidth: 3,
    buttonFontSize: 32,
    buttonPulse: 10,
    promptLetterSpacing: 3,
    promptRadius: 3,
    flashSize: 250,
    flashIntensity: 100,
    ambientGlow: 80,
    sparkCount: 12,
    motionSpeed: 1.6,
  }),
  preset("arcane-seal", "秘术刻印", "幻想", "金紫色旋转刻印，适合法术与仪式判定。", {
    overlayColor: "#0B06155C",
    overlayBlur: 3,
    outerRingColor: "#D7B6FFFF",
    outerTrackColor: "#A06BFF2B",
    perfectColor: "#FFD978",
    tickColor: "#C69CFFB3",
    buttonBgColor: "#1F1138ED",
    buttonTextColor: "#FFF7DC",
    buttonBorderColor: "#E2C6FFB8",
    buttonAccentColor: "#FFD978",
    promptColor: "#FFF4D6",
    promptBgColor: "#180C2BD6",
    progressColor: "#D7B6FF",
    flashColor: "#FFD978D9",
    ringPattern: "segmented",
    buttonShape: "diamond",
    ringStroke: 5,
    ringGlow: 58,
    ringRotationSpeed: 20,
    tickCount: 24,
    tickLength: 9,
    buttonSize: 82,
    buttonBorderWidth: 2,
    buttonFontSize: 27,
    buttonShadow: 42,
    buttonPulse: 5,
    promptLetterSpacing: 2,
    promptRadius: 14,
    flashSize: 280,
    flashIntensity: 86,
    ambientGlow: 108,
    sparkCount: 20,
    motionSpeed: 0.8,
  }),
  preset("sakura-heartbeat", "樱色心跳", "幻想", "柔和樱粉与呼吸感，适合情感节点。", {
    overlayColor: "#32142147",
    overlayBlur: 5,
    outerRingColor: "#FFD5E8E6",
    outerTrackColor: "#FF91BE2E",
    perfectColor: "#FFF0A6",
    tickColor: "#FFB5D0A3",
    buttonBgColor: "#6B244BD9",
    buttonTextColor: "#FFF8FB",
    buttonBorderColor: "#FFD2E5CC",
    buttonAccentColor: "#FF84B7",
    promptColor: "#FFF8FB",
    promptBgColor: "#5B1C3BB8",
    progressColor: "#FFD5E8",
    flashColor: "#FFF0A6C7",
    ringPattern: "dashed",
    ringGlow: 42,
    ringRotationSpeed: 10,
    tickCount: 10,
    tickLength: 7,
    buttonSize: 94,
    buttonBorderWidth: 2,
    buttonFontSize: 30,
    buttonPulse: 7,
    promptRadius: 16,
    flashSize: 230,
    ambientGlow: 84,
    sparkCount: 14,
    motionSpeed: 0.7,
  }),
  preset("frost-sight", "霜蓝瞄准", "氛围", "低温蓝白准星，适合潜行、调查与狙击。", {
    overlayColor: "#03111F70",
    overlayBlur: 1,
    outerRingColor: "#B8EDFFFF",
    outerTrackColor: "#49BCE52E",
    perfectColor: "#FFFFFF",
    tickColor: "#65D7FFB8",
    buttonBgColor: "#071D2CEB",
    buttonTextColor: "#E9FAFF",
    buttonBorderColor: "#9BE5FFB8",
    buttonAccentColor: "#4ED2FF",
    promptColor: "#E8FAFF",
    promptBgColor: "#061923CC",
    progressColor: "#72DCFF",
    flashColor: "#D7F7FFE0",
    ringPattern: "solid",
    ringStroke: 3,
    ringGlow: 38,
    ringRotationSpeed: 0,
    tickCount: 20,
    tickLength: 14,
    buttonSize: 78,
    buttonBorderWidth: 1,
    buttonFontSize: 25,
    buttonPulse: 2,
    promptFontSize: 14,
    promptLetterSpacing: 4,
    promptWeight: "regular",
    flashSize: 210,
    flashIntensity: 70,
    ambientGlow: 72,
    sparkCount: 6,
    motionSpeed: 0.8,
  }),
  preset("amber-machine", "琥珀机巧", "氛围", "工业琥珀色方环，适合机关和机械交互。", {
    overlayColor: "#110C0370",
    outerRingColor: "#FFD26AFF",
    outerTrackColor: "#FFB32629",
    perfectColor: "#FFF2B0",
    tickColor: "#FFBF47CC",
    buttonBgColor: "#2B1C08F2",
    buttonTextColor: "#FFF4D1",
    buttonBorderColor: "#EAAE3FCC",
    buttonAccentColor: "#FFB326",
    promptColor: "#FFF2CE",
    promptBgColor: "#2A1906E3",
    progressColor: "#FFD26A",
    flashColor: "#FFCB5CE0",
    ringShape: "rounded-square",
    ringPattern: "segmented",
    buttonShape: "rounded",
    ringDiameter: 310,
    ringStroke: 8,
    ringGlow: 32,
    ringRotationSpeed: 20,
    tickCount: 12,
    tickLength: 15,
    buttonSize: 90,
    buttonBorderWidth: 3,
    buttonFontSize: 29,
    buttonShadow: 30,
    buttonPulse: 6,
    promptLetterSpacing: 1.6,
    promptRadius: 4,
    flashSize: 240,
    flashIntensity: 82,
    ambientGlow: 62,
    sparkCount: 10,
    motionSpeed: 1.1,
  }),
];

export const QTE_PRESET_CATEGORIES: readonly ("全部" | QtePresetCategory)[] = [
  "全部",
  "基础",
  "动作",
  "幻想",
  "氛围",
];

export function matchesQtePreset(style: QteResolvedStyle, preset: QteStylePreset): boolean {
  return Object.keys(style).every((key) => {
    const field = key as keyof QteResolvedStyle;
    return style[field] === preset.style[field];
  });
}
